# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36e5b312999d6b3c3fb8034eac1d688585a22ec23d4dc8dd1b9e847a39882b7ee8f7b12bd3457d056e9b7aa3d8f68bba399e4c04388128475a9fd470ff167b65

test:
  secret_key_base: 23f1b5eff8a7781a0cfa9938bd574ef37565e6377993ade6127c93313cd4d4920d367f01742a296d93af82e6d3128dfeb6ee7389862da2d2a279ee0bb10cc5b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
